feat: add files option
xlayers/version-stamp pull request #7
Opened 2021-02-13 10:32 UTC by chihab

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #6

## What is the new behavior?

New files option where we can put  the list of file patterns containing `_BUILD_HASH_`

Example:
```sh
ng run <your-app>:stamp --files=*.js,*.json
```

Also configurable from builder options in angular|workspace.json

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-02-13 14:27 UTC, manekinekko approved these changes
LGTM

2021-02-14 14:06 UTC, Jefiozie requested changes
Hey @chihab, thank you so much for this PR! I've made some small suggestions could you have a look at it?
I would like to lean on the defaults we can use from the schema, would you agree on this?

Let me know what you think about it and again thanks for using this lib and providing us with this PR and feedback. 🙏

2021-02-14 14:06 UTC, Jefiozie commented on packages/version-stamp/src/lib/stamp/schema.json
>        "$valueDescription": "configuration"
```suggestion
    "files": {
      "type": "array",
      "description": "The list of patterns to match the files with",
      "$valueDescription": "configuration",
      default":  ["*.js", "*.json"]
```

2021-02-14 14:06 UTC, Jefiozie commented on packages/version-stamp/src/lib/stamp/index.ts
> +          files: options.files.length ? options.files : ['*.js', '*.json'],
```suggestion
          files: options.files,
```

2021-02-14 14:06 UTC, Jefiozie commented on workspace.json
> +            "files": ["*.js", "*.json"]
```suggestion
```

2021-02-14 19:41 UTC, Jefiozie approved these changes
LGTM

2021-02-14 19:42 UTC, merged